### ISSUE TITLE
Include instructions on getting token in `README.md`

### ISSUE THREAD

**Issue by jlumbroso** [seratch/python-slack-scim#3]
This is a wonderful library!

The token that the `README.md` suggests using, seems to be described as a "Legacy Token" by [the official Slack documentation](https://slack.com/help/articles/215770388-Create-and-regenerate-API-tokens). Other instructions are not very straightforward.

I would link directly to instructions within the `README.md`:

> As explained in [the official Slack SCIM API documentation](https://api.slack.com/scim#access), the easiest way to obtain a valid token for the purposes of SCIM provisioning are:
> 1. As *a Workspace/Organization Owner*, create [a new app for your workspace](https://api.slack.com/apps?new_app=1) (see [here](https://api.slack.com/start/overview#creating) for the documentation).
> 2. Add the `admin` OAuth scope to [the "User Token Scopes" section](https://api.slack.com/authentication/quickstart#configuring).
> 3. Install the app to your workspace (see [here](https://api.slack.com/start/overview#installing_distributing) for the documentation).
> 4. Use the generated token (if you are provided with multiple tokens, use the "OAuth Access Token" not the "Bot User OAuth Access Token").
>
> Note that you can easily *reinstall your app* with different permissions if it turns out you did not select all the necessary permissions.

Indeed, one of the most challenging things for users of an SDK is figuring out how to obtain the right credentials. This is made more difficult by Slack's multiple changes of authentication method, and at times inconsistent terminology.

**Comment by jlumbroso** [comment]
@seratch In case you're interested in making this change, I've created a pull request: https://github.com/seratch/python-slack-scim/pull/4

**Comment by seratch** [comment]
Thank you! I meant the token by "your admin user token" but indeed, it was not so easy to understand for many.
